version: "2"
sql:
  - engine: "postgresql"
    queries: "query.sql"
    schema: "migrations/"
    gen:
      go:
        package: "sqlc"
        out: "sqlc"
        sql_package: "pgx/v5"
        overrides:
          - db_type: "uuid"
            go_type:
              import: "github.com/google/uuid"
              type: "UUID"
              pointer: true
            # nullable: true
          - column: "*.schedule_id"
            go_type:
              import: "github.com/google/uuid"
              type: "UUID"
              pointer: true
            # nullable: true
          - column: "*.task_id"
            go_type:
              import: "github.com/google/uuid"
              type: "UUID"
              pointer: true
            # nullable: true
          - column: "*.worker_id"
            go_type:
              import: "github.com/google/uuid"
              type: "UUID"
              pointer: true
            # nullable: true
          - column: "*.location_id"
            go_type:
              import: "github.com/google/uuid"
              type: "UUID"
              pointer: true
            # nullable: true
