// Code generated by mockery v2.50.1. DO NOT EDIT.

package mocks

import (
	context "context"

	ports "github.com/pavozayac/constraints/internal/domain/ports"
	mock "github.com/stretchr/testify/mock"
)

// MockWorkerService is an autogenerated mock type for the WorkerService type
type MockWorkerService struct {
	mock.Mock
}

type MockWorkerService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkerService) EXPECT() *MockWorkerService_Expecter {
	return &MockWorkerService_Expecter{mock: &_m.Mock}
}

// CreateOrModifyWorker provides a mock function with given fields: _a0, _a1
func (_m *MockWorkerService) CreateOrModifyWorker(_a0 context.Context, _a1 ports.WorkerDTO) (*ports.WorkerDTO, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrModifyWorker")
	}

	var r0 *ports.WorkerDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ports.WorkerDTO) (*ports.WorkerDTO, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ports.WorkerDTO) *ports.WorkerDTO); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.WorkerDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ports.WorkerDTO) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkerService_CreateOrModifyWorker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrModifyWorker'
type MockWorkerService_CreateOrModifyWorker_Call struct {
	*mock.Call
}

// CreateOrModifyWorker is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 ports.WorkerDTO
func (_e *MockWorkerService_Expecter) CreateOrModifyWorker(_a0 interface{}, _a1 interface{}) *MockWorkerService_CreateOrModifyWorker_Call {
	return &MockWorkerService_CreateOrModifyWorker_Call{Call: _e.mock.On("CreateOrModifyWorker", _a0, _a1)}
}

func (_c *MockWorkerService_CreateOrModifyWorker_Call) Run(run func(_a0 context.Context, _a1 ports.WorkerDTO)) *MockWorkerService_CreateOrModifyWorker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ports.WorkerDTO))
	})
	return _c
}

func (_c *MockWorkerService_CreateOrModifyWorker_Call) Return(_a0 *ports.WorkerDTO, _a1 error) *MockWorkerService_CreateOrModifyWorker_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkerService_CreateOrModifyWorker_Call) RunAndReturn(run func(context.Context, ports.WorkerDTO) (*ports.WorkerDTO, error)) *MockWorkerService_CreateOrModifyWorker_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorker provides a mock function with given fields: _a0, _a1
func (_m *MockWorkerService) GetWorker(_a0 context.Context, _a1 string) (*ports.WorkerDTO, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetWorker")
	}

	var r0 *ports.WorkerDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ports.WorkerDTO, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ports.WorkerDTO); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.WorkerDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkerService_GetWorker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorker'
type MockWorkerService_GetWorker_Call struct {
	*mock.Call
}

// GetWorker is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockWorkerService_Expecter) GetWorker(_a0 interface{}, _a1 interface{}) *MockWorkerService_GetWorker_Call {
	return &MockWorkerService_GetWorker_Call{Call: _e.mock.On("GetWorker", _a0, _a1)}
}

func (_c *MockWorkerService_GetWorker_Call) Run(run func(_a0 context.Context, _a1 string)) *MockWorkerService_GetWorker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockWorkerService_GetWorker_Call) Return(_a0 *ports.WorkerDTO, _a1 error) *MockWorkerService_GetWorker_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkerService_GetWorker_Call) RunAndReturn(run func(context.Context, string) (*ports.WorkerDTO, error)) *MockWorkerService_GetWorker_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveWorker provides a mock function with given fields: _a0, _a1
func (_m *MockWorkerService) RemoveWorker(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for RemoveWorker")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWorkerService_RemoveWorker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveWorker'
type MockWorkerService_RemoveWorker_Call struct {
	*mock.Call
}

// RemoveWorker is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockWorkerService_Expecter) RemoveWorker(_a0 interface{}, _a1 interface{}) *MockWorkerService_RemoveWorker_Call {
	return &MockWorkerService_RemoveWorker_Call{Call: _e.mock.On("RemoveWorker", _a0, _a1)}
}

func (_c *MockWorkerService_RemoveWorker_Call) Run(run func(_a0 context.Context, _a1 string)) *MockWorkerService_RemoveWorker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockWorkerService_RemoveWorker_Call) Return(_a0 error) *MockWorkerService_RemoveWorker_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWorkerService_RemoveWorker_Call) RunAndReturn(run func(context.Context, string) error) *MockWorkerService_RemoveWorker_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWorkerService creates a new instance of MockWorkerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkerService {
	mock := &MockWorkerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
