// Code generated by mockery v2.50.1. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/pavozayac/constraints/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	shared "github.com/pavozayac/constraints/internal/domain/shared"
)

// MockLocationRepository is an autogenerated mock type for the LocationRepository type
type MockLocationRepository struct {
	mock.Mock
}

type MockLocationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLocationRepository) EXPECT() *MockLocationRepository_Expecter {
	return &MockLocationRepository_Expecter{mock: &_m.Mock}
}

// DeleteLocation provides a mock function with given fields: _a0, _a1
func (_m *MockLocationRepository) DeleteLocation(_a0 context.Context, _a1 shared.Identity) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLocation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, shared.Identity) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLocationRepository_DeleteLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLocation'
type MockLocationRepository_DeleteLocation_Call struct {
	*mock.Call
}

// DeleteLocation is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 shared.Identity
func (_e *MockLocationRepository_Expecter) DeleteLocation(_a0 interface{}, _a1 interface{}) *MockLocationRepository_DeleteLocation_Call {
	return &MockLocationRepository_DeleteLocation_Call{Call: _e.mock.On("DeleteLocation", _a0, _a1)}
}

func (_c *MockLocationRepository_DeleteLocation_Call) Run(run func(_a0 context.Context, _a1 shared.Identity)) *MockLocationRepository_DeleteLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(shared.Identity))
	})
	return _c
}

func (_c *MockLocationRepository_DeleteLocation_Call) Return(_a0 error) *MockLocationRepository_DeleteLocation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLocationRepository_DeleteLocation_Call) RunAndReturn(run func(context.Context, shared.Identity) error) *MockLocationRepository_DeleteLocation_Call {
	_c.Call.Return(run)
	return _c
}

// GetLocation provides a mock function with given fields: _a0, _a1
func (_m *MockLocationRepository) GetLocation(_a0 context.Context, _a1 shared.Identity) (*model.Location, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetLocation")
	}

	var r0 *model.Location
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, shared.Identity) (*model.Location, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, shared.Identity) *model.Location); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Location)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, shared.Identity) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLocationRepository_GetLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLocation'
type MockLocationRepository_GetLocation_Call struct {
	*mock.Call
}

// GetLocation is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 shared.Identity
func (_e *MockLocationRepository_Expecter) GetLocation(_a0 interface{}, _a1 interface{}) *MockLocationRepository_GetLocation_Call {
	return &MockLocationRepository_GetLocation_Call{Call: _e.mock.On("GetLocation", _a0, _a1)}
}

func (_c *MockLocationRepository_GetLocation_Call) Run(run func(_a0 context.Context, _a1 shared.Identity)) *MockLocationRepository_GetLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(shared.Identity))
	})
	return _c
}

func (_c *MockLocationRepository_GetLocation_Call) Return(_a0 *model.Location, _a1 error) *MockLocationRepository_GetLocation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLocationRepository_GetLocation_Call) RunAndReturn(run func(context.Context, shared.Identity) (*model.Location, error)) *MockLocationRepository_GetLocation_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOrUpdateLocation provides a mock function with given fields: _a0, _a1
func (_m *MockLocationRepository) SaveOrUpdateLocation(_a0 context.Context, _a1 model.Location) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SaveOrUpdateLocation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Location) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLocationRepository_SaveOrUpdateLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOrUpdateLocation'
type MockLocationRepository_SaveOrUpdateLocation_Call struct {
	*mock.Call
}

// SaveOrUpdateLocation is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 model.Location
func (_e *MockLocationRepository_Expecter) SaveOrUpdateLocation(_a0 interface{}, _a1 interface{}) *MockLocationRepository_SaveOrUpdateLocation_Call {
	return &MockLocationRepository_SaveOrUpdateLocation_Call{Call: _e.mock.On("SaveOrUpdateLocation", _a0, _a1)}
}

func (_c *MockLocationRepository_SaveOrUpdateLocation_Call) Run(run func(_a0 context.Context, _a1 model.Location)) *MockLocationRepository_SaveOrUpdateLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Location))
	})
	return _c
}

func (_c *MockLocationRepository_SaveOrUpdateLocation_Call) Return(_a0 error) *MockLocationRepository_SaveOrUpdateLocation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLocationRepository_SaveOrUpdateLocation_Call) RunAndReturn(run func(context.Context, model.Location) error) *MockLocationRepository_SaveOrUpdateLocation_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLocationRepository creates a new instance of MockLocationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLocationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLocationRepository {
	mock := &MockLocationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
