// Code generated by mockery v2.50.1. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/pavozayac/constraints/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	shared "github.com/pavozayac/constraints/internal/domain/shared"
)

// MockWorkerRepository is an autogenerated mock type for the WorkerRepository type
type MockWorkerRepository struct {
	mock.Mock
}

type MockWorkerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkerRepository) EXPECT() *MockWorkerRepository_Expecter {
	return &MockWorkerRepository_Expecter{mock: &_m.Mock}
}

// DeleteWorker provides a mock function with given fields: _a0, _a1
func (_m *MockWorkerRepository) DeleteWorker(_a0 context.Context, _a1 shared.Identity) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWorker")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, shared.Identity) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWorkerRepository_DeleteWorker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWorker'
type MockWorkerRepository_DeleteWorker_Call struct {
	*mock.Call
}

// DeleteWorker is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 shared.Identity
func (_e *MockWorkerRepository_Expecter) DeleteWorker(_a0 interface{}, _a1 interface{}) *MockWorkerRepository_DeleteWorker_Call {
	return &MockWorkerRepository_DeleteWorker_Call{Call: _e.mock.On("DeleteWorker", _a0, _a1)}
}

func (_c *MockWorkerRepository_DeleteWorker_Call) Run(run func(_a0 context.Context, _a1 shared.Identity)) *MockWorkerRepository_DeleteWorker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(shared.Identity))
	})
	return _c
}

func (_c *MockWorkerRepository_DeleteWorker_Call) Return(_a0 error) *MockWorkerRepository_DeleteWorker_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWorkerRepository_DeleteWorker_Call) RunAndReturn(run func(context.Context, shared.Identity) error) *MockWorkerRepository_DeleteWorker_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorker provides a mock function with given fields: _a0, _a1
func (_m *MockWorkerRepository) GetWorker(_a0 context.Context, _a1 shared.Identity) (*model.Worker, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetWorker")
	}

	var r0 *model.Worker
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, shared.Identity) (*model.Worker, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, shared.Identity) *model.Worker); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Worker)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, shared.Identity) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkerRepository_GetWorker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorker'
type MockWorkerRepository_GetWorker_Call struct {
	*mock.Call
}

// GetWorker is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 shared.Identity
func (_e *MockWorkerRepository_Expecter) GetWorker(_a0 interface{}, _a1 interface{}) *MockWorkerRepository_GetWorker_Call {
	return &MockWorkerRepository_GetWorker_Call{Call: _e.mock.On("GetWorker", _a0, _a1)}
}

func (_c *MockWorkerRepository_GetWorker_Call) Run(run func(_a0 context.Context, _a1 shared.Identity)) *MockWorkerRepository_GetWorker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(shared.Identity))
	})
	return _c
}

func (_c *MockWorkerRepository_GetWorker_Call) Return(_a0 *model.Worker, _a1 error) *MockWorkerRepository_GetWorker_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkerRepository_GetWorker_Call) RunAndReturn(run func(context.Context, shared.Identity) (*model.Worker, error)) *MockWorkerRepository_GetWorker_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOrUpdateWorker provides a mock function with given fields: _a0, _a1
func (_m *MockWorkerRepository) SaveOrUpdateWorker(_a0 context.Context, _a1 model.Worker) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SaveOrUpdateWorker")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Worker) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWorkerRepository_SaveOrUpdateWorker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOrUpdateWorker'
type MockWorkerRepository_SaveOrUpdateWorker_Call struct {
	*mock.Call
}

// SaveOrUpdateWorker is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 model.Worker
func (_e *MockWorkerRepository_Expecter) SaveOrUpdateWorker(_a0 interface{}, _a1 interface{}) *MockWorkerRepository_SaveOrUpdateWorker_Call {
	return &MockWorkerRepository_SaveOrUpdateWorker_Call{Call: _e.mock.On("SaveOrUpdateWorker", _a0, _a1)}
}

func (_c *MockWorkerRepository_SaveOrUpdateWorker_Call) Run(run func(_a0 context.Context, _a1 model.Worker)) *MockWorkerRepository_SaveOrUpdateWorker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Worker))
	})
	return _c
}

func (_c *MockWorkerRepository_SaveOrUpdateWorker_Call) Return(_a0 error) *MockWorkerRepository_SaveOrUpdateWorker_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWorkerRepository_SaveOrUpdateWorker_Call) RunAndReturn(run func(context.Context, model.Worker) error) *MockWorkerRepository_SaveOrUpdateWorker_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWorkerRepository creates a new instance of MockWorkerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkerRepository {
	mock := &MockWorkerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
