// Code generated by mockery v2.50.1. DO NOT EDIT.

package mocks

import (
	context "context"

	ports "github.com/pavozayac/constraints/internal/domain/ports"
	mock "github.com/stretchr/testify/mock"
)

// MockTaskService is an autogenerated mock type for the TaskService type
type MockTaskService struct {
	mock.Mock
}

type MockTaskService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskService) EXPECT() *MockTaskService_Expecter {
	return &MockTaskService_Expecter{mock: &_m.Mock}
}

// CreateOrModifyTask provides a mock function with given fields: _a0, _a1
func (_m *MockTaskService) CreateOrModifyTask(_a0 context.Context, _a1 ports.TaskDTO) (*ports.TaskDTO, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrModifyTask")
	}

	var r0 *ports.TaskDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ports.TaskDTO) (*ports.TaskDTO, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ports.TaskDTO) *ports.TaskDTO); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.TaskDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ports.TaskDTO) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_CreateOrModifyTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrModifyTask'
type MockTaskService_CreateOrModifyTask_Call struct {
	*mock.Call
}

// CreateOrModifyTask is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 ports.TaskDTO
func (_e *MockTaskService_Expecter) CreateOrModifyTask(_a0 interface{}, _a1 interface{}) *MockTaskService_CreateOrModifyTask_Call {
	return &MockTaskService_CreateOrModifyTask_Call{Call: _e.mock.On("CreateOrModifyTask", _a0, _a1)}
}

func (_c *MockTaskService_CreateOrModifyTask_Call) Run(run func(_a0 context.Context, _a1 ports.TaskDTO)) *MockTaskService_CreateOrModifyTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ports.TaskDTO))
	})
	return _c
}

func (_c *MockTaskService_CreateOrModifyTask_Call) Return(_a0 *ports.TaskDTO, _a1 error) *MockTaskService_CreateOrModifyTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_CreateOrModifyTask_Call) RunAndReturn(run func(context.Context, ports.TaskDTO) (*ports.TaskDTO, error)) *MockTaskService_CreateOrModifyTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetTask provides a mock function with given fields: _a0, _a1
func (_m *MockTaskService) GetTask(_a0 context.Context, _a1 string) (*ports.TaskDTO, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 *ports.TaskDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ports.TaskDTO, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ports.TaskDTO); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.TaskDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskService_GetTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTask'
type MockTaskService_GetTask_Call struct {
	*mock.Call
}

// GetTask is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockTaskService_Expecter) GetTask(_a0 interface{}, _a1 interface{}) *MockTaskService_GetTask_Call {
	return &MockTaskService_GetTask_Call{Call: _e.mock.On("GetTask", _a0, _a1)}
}

func (_c *MockTaskService_GetTask_Call) Run(run func(_a0 context.Context, _a1 string)) *MockTaskService_GetTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskService_GetTask_Call) Return(_a0 *ports.TaskDTO, _a1 error) *MockTaskService_GetTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskService_GetTask_Call) RunAndReturn(run func(context.Context, string) (*ports.TaskDTO, error)) *MockTaskService_GetTask_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveTask provides a mock function with given fields: _a0, _a1
func (_m *MockTaskService) RemoveTask(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for RemoveTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskService_RemoveTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveTask'
type MockTaskService_RemoveTask_Call struct {
	*mock.Call
}

// RemoveTask is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockTaskService_Expecter) RemoveTask(_a0 interface{}, _a1 interface{}) *MockTaskService_RemoveTask_Call {
	return &MockTaskService_RemoveTask_Call{Call: _e.mock.On("RemoveTask", _a0, _a1)}
}

func (_c *MockTaskService_RemoveTask_Call) Run(run func(_a0 context.Context, _a1 string)) *MockTaskService_RemoveTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTaskService_RemoveTask_Call) Return(_a0 error) *MockTaskService_RemoveTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskService_RemoveTask_Call) RunAndReturn(run func(context.Context, string) error) *MockTaskService_RemoveTask_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskService creates a new instance of MockTaskService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskService {
	mock := &MockTaskService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
