// Code generated by mockery v2.50.1. DO NOT EDIT.

package mocks

import (
	context "context"

	ports "github.com/pavozayac/constraints/internal/domain/ports"
	mock "github.com/stretchr/testify/mock"
)

// MockLocationService is an autogenerated mock type for the LocationService type
type MockLocationService struct {
	mock.Mock
}

type MockLocationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLocationService) EXPECT() *MockLocationService_Expecter {
	return &MockLocationService_Expecter{mock: &_m.Mock}
}

// CreateOrModifyLocation provides a mock function with given fields: _a0, _a1
func (_m *MockLocationService) CreateOrModifyLocation(_a0 context.Context, _a1 ports.LocationDTO) (*ports.LocationDTO, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrModifyLocation")
	}

	var r0 *ports.LocationDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ports.LocationDTO) (*ports.LocationDTO, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ports.LocationDTO) *ports.LocationDTO); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.LocationDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ports.LocationDTO) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLocationService_CreateOrModifyLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrModifyLocation'
type MockLocationService_CreateOrModifyLocation_Call struct {
	*mock.Call
}

// CreateOrModifyLocation is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 ports.LocationDTO
func (_e *MockLocationService_Expecter) CreateOrModifyLocation(_a0 interface{}, _a1 interface{}) *MockLocationService_CreateOrModifyLocation_Call {
	return &MockLocationService_CreateOrModifyLocation_Call{Call: _e.mock.On("CreateOrModifyLocation", _a0, _a1)}
}

func (_c *MockLocationService_CreateOrModifyLocation_Call) Run(run func(_a0 context.Context, _a1 ports.LocationDTO)) *MockLocationService_CreateOrModifyLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ports.LocationDTO))
	})
	return _c
}

func (_c *MockLocationService_CreateOrModifyLocation_Call) Return(_a0 *ports.LocationDTO, _a1 error) *MockLocationService_CreateOrModifyLocation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLocationService_CreateOrModifyLocation_Call) RunAndReturn(run func(context.Context, ports.LocationDTO) (*ports.LocationDTO, error)) *MockLocationService_CreateOrModifyLocation_Call {
	_c.Call.Return(run)
	return _c
}

// GetLocation provides a mock function with given fields: _a0, _a1
func (_m *MockLocationService) GetLocation(_a0 context.Context, _a1 string) (*ports.LocationDTO, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetLocation")
	}

	var r0 *ports.LocationDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ports.LocationDTO, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ports.LocationDTO); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.LocationDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLocationService_GetLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLocation'
type MockLocationService_GetLocation_Call struct {
	*mock.Call
}

// GetLocation is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockLocationService_Expecter) GetLocation(_a0 interface{}, _a1 interface{}) *MockLocationService_GetLocation_Call {
	return &MockLocationService_GetLocation_Call{Call: _e.mock.On("GetLocation", _a0, _a1)}
}

func (_c *MockLocationService_GetLocation_Call) Run(run func(_a0 context.Context, _a1 string)) *MockLocationService_GetLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLocationService_GetLocation_Call) Return(_a0 *ports.LocationDTO, _a1 error) *MockLocationService_GetLocation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLocationService_GetLocation_Call) RunAndReturn(run func(context.Context, string) (*ports.LocationDTO, error)) *MockLocationService_GetLocation_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveLocation provides a mock function with given fields: _a0, _a1
func (_m *MockLocationService) RemoveLocation(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for RemoveLocation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLocationService_RemoveLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveLocation'
type MockLocationService_RemoveLocation_Call struct {
	*mock.Call
}

// RemoveLocation is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockLocationService_Expecter) RemoveLocation(_a0 interface{}, _a1 interface{}) *MockLocationService_RemoveLocation_Call {
	return &MockLocationService_RemoveLocation_Call{Call: _e.mock.On("RemoveLocation", _a0, _a1)}
}

func (_c *MockLocationService_RemoveLocation_Call) Run(run func(_a0 context.Context, _a1 string)) *MockLocationService_RemoveLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLocationService_RemoveLocation_Call) Return(_a0 error) *MockLocationService_RemoveLocation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLocationService_RemoveLocation_Call) RunAndReturn(run func(context.Context, string) error) *MockLocationService_RemoveLocation_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLocationService creates a new instance of MockLocationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLocationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLocationService {
	mock := &MockLocationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
