// Code generated by mockery v2.50.1. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/pavozayac/constraints/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	shared "github.com/pavozayac/constraints/internal/domain/shared"
)

// MockTaskRepository is an autogenerated mock type for the TaskRepository type
type MockTaskRepository struct {
	mock.Mock
}

type MockTaskRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskRepository) EXPECT() *MockTaskRepository_Expecter {
	return &MockTaskRepository_Expecter{mock: &_m.Mock}
}

// DeleteTask provides a mock function with given fields: _a0, _a1
func (_m *MockTaskRepository) DeleteTask(_a0 context.Context, _a1 shared.Identity) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, shared.Identity) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskRepository_DeleteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTask'
type MockTaskRepository_DeleteTask_Call struct {
	*mock.Call
}

// DeleteTask is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 shared.Identity
func (_e *MockTaskRepository_Expecter) DeleteTask(_a0 interface{}, _a1 interface{}) *MockTaskRepository_DeleteTask_Call {
	return &MockTaskRepository_DeleteTask_Call{Call: _e.mock.On("DeleteTask", _a0, _a1)}
}

func (_c *MockTaskRepository_DeleteTask_Call) Run(run func(_a0 context.Context, _a1 shared.Identity)) *MockTaskRepository_DeleteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(shared.Identity))
	})
	return _c
}

func (_c *MockTaskRepository_DeleteTask_Call) Return(_a0 error) *MockTaskRepository_DeleteTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskRepository_DeleteTask_Call) RunAndReturn(run func(context.Context, shared.Identity) error) *MockTaskRepository_DeleteTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetTask provides a mock function with given fields: _a0, _a1
func (_m *MockTaskRepository) GetTask(_a0 context.Context, _a1 shared.Identity) (*model.Task, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 *model.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, shared.Identity) (*model.Task, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, shared.Identity) *model.Task); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, shared.Identity) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTaskRepository_GetTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTask'
type MockTaskRepository_GetTask_Call struct {
	*mock.Call
}

// GetTask is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 shared.Identity
func (_e *MockTaskRepository_Expecter) GetTask(_a0 interface{}, _a1 interface{}) *MockTaskRepository_GetTask_Call {
	return &MockTaskRepository_GetTask_Call{Call: _e.mock.On("GetTask", _a0, _a1)}
}

func (_c *MockTaskRepository_GetTask_Call) Run(run func(_a0 context.Context, _a1 shared.Identity)) *MockTaskRepository_GetTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(shared.Identity))
	})
	return _c
}

func (_c *MockTaskRepository_GetTask_Call) Return(_a0 *model.Task, _a1 error) *MockTaskRepository_GetTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTaskRepository_GetTask_Call) RunAndReturn(run func(context.Context, shared.Identity) (*model.Task, error)) *MockTaskRepository_GetTask_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOrUpdateTask provides a mock function with given fields: _a0, _a1
func (_m *MockTaskRepository) SaveOrUpdateTask(_a0 context.Context, _a1 model.Task) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SaveOrUpdateTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Task) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTaskRepository_SaveOrUpdateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOrUpdateTask'
type MockTaskRepository_SaveOrUpdateTask_Call struct {
	*mock.Call
}

// SaveOrUpdateTask is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 model.Task
func (_e *MockTaskRepository_Expecter) SaveOrUpdateTask(_a0 interface{}, _a1 interface{}) *MockTaskRepository_SaveOrUpdateTask_Call {
	return &MockTaskRepository_SaveOrUpdateTask_Call{Call: _e.mock.On("SaveOrUpdateTask", _a0, _a1)}
}

func (_c *MockTaskRepository_SaveOrUpdateTask_Call) Run(run func(_a0 context.Context, _a1 model.Task)) *MockTaskRepository_SaveOrUpdateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Task))
	})
	return _c
}

func (_c *MockTaskRepository_SaveOrUpdateTask_Call) Return(_a0 error) *MockTaskRepository_SaveOrUpdateTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTaskRepository_SaveOrUpdateTask_Call) RunAndReturn(run func(context.Context, model.Task) error) *MockTaskRepository_SaveOrUpdateTask_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTaskRepository creates a new instance of MockTaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskRepository {
	mock := &MockTaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
