// Code generated by mockery v2.50.1. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/pavozayac/scheduling/src/constraint-service/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	shared "github.com/pavozayac/scheduling/src/constraint-service/internal/domain/shared"
)

// MockScheduleRepository is an autogenerated mock type for the ScheduleRepository type
type MockScheduleRepository struct {
	mock.Mock
}

type MockScheduleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScheduleRepository) EXPECT() *MockScheduleRepository_Expecter {
	return &MockScheduleRepository_Expecter{mock: &_m.Mock}
}

// DeleteSchedule provides a mock function with given fields: _a0, _a1
func (_m *MockScheduleRepository) DeleteSchedule(_a0 context.Context, _a1 shared.Identity) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSchedule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, shared.Identity) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockScheduleRepository_DeleteSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSchedule'
type MockScheduleRepository_DeleteSchedule_Call struct {
	*mock.Call
}

// DeleteSchedule is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 shared.Identity
func (_e *MockScheduleRepository_Expecter) DeleteSchedule(_a0 interface{}, _a1 interface{}) *MockScheduleRepository_DeleteSchedule_Call {
	return &MockScheduleRepository_DeleteSchedule_Call{Call: _e.mock.On("DeleteSchedule", _a0, _a1)}
}

func (_c *MockScheduleRepository_DeleteSchedule_Call) Run(run func(_a0 context.Context, _a1 shared.Identity)) *MockScheduleRepository_DeleteSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(shared.Identity))
	})
	return _c
}

func (_c *MockScheduleRepository_DeleteSchedule_Call) Return(_a0 error) *MockScheduleRepository_DeleteSchedule_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockScheduleRepository_DeleteSchedule_Call) RunAndReturn(run func(context.Context, shared.Identity) error) *MockScheduleRepository_DeleteSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// GetSchedule provides a mock function with given fields: _a0, _a1
func (_m *MockScheduleRepository) GetSchedule(_a0 context.Context, _a1 shared.Identity) (*model.Schedule, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetSchedule")
	}

	var r0 *model.Schedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, shared.Identity) (*model.Schedule, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, shared.Identity) *model.Schedule); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Schedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, shared.Identity) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockScheduleRepository_GetSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSchedule'
type MockScheduleRepository_GetSchedule_Call struct {
	*mock.Call
}

// GetSchedule is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 shared.Identity
func (_e *MockScheduleRepository_Expecter) GetSchedule(_a0 interface{}, _a1 interface{}) *MockScheduleRepository_GetSchedule_Call {
	return &MockScheduleRepository_GetSchedule_Call{Call: _e.mock.On("GetSchedule", _a0, _a1)}
}

func (_c *MockScheduleRepository_GetSchedule_Call) Run(run func(_a0 context.Context, _a1 shared.Identity)) *MockScheduleRepository_GetSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(shared.Identity))
	})
	return _c
}

func (_c *MockScheduleRepository_GetSchedule_Call) Return(_a0 *model.Schedule, _a1 error) *MockScheduleRepository_GetSchedule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockScheduleRepository_GetSchedule_Call) RunAndReturn(run func(context.Context, shared.Identity) (*model.Schedule, error)) *MockScheduleRepository_GetSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOrUpdateSchedule provides a mock function with given fields: _a0, _a1
func (_m *MockScheduleRepository) SaveOrUpdateSchedule(_a0 context.Context, _a1 model.Schedule) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SaveOrUpdateSchedule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Schedule) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockScheduleRepository_SaveOrUpdateSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOrUpdateSchedule'
type MockScheduleRepository_SaveOrUpdateSchedule_Call struct {
	*mock.Call
}

// SaveOrUpdateSchedule is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 model.Schedule
func (_e *MockScheduleRepository_Expecter) SaveOrUpdateSchedule(_a0 interface{}, _a1 interface{}) *MockScheduleRepository_SaveOrUpdateSchedule_Call {
	return &MockScheduleRepository_SaveOrUpdateSchedule_Call{Call: _e.mock.On("SaveOrUpdateSchedule", _a0, _a1)}
}

func (_c *MockScheduleRepository_SaveOrUpdateSchedule_Call) Run(run func(_a0 context.Context, _a1 model.Schedule)) *MockScheduleRepository_SaveOrUpdateSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Schedule))
	})
	return _c
}

func (_c *MockScheduleRepository_SaveOrUpdateSchedule_Call) Return(_a0 error) *MockScheduleRepository_SaveOrUpdateSchedule_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockScheduleRepository_SaveOrUpdateSchedule_Call) RunAndReturn(run func(context.Context, model.Schedule) error) *MockScheduleRepository_SaveOrUpdateSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockScheduleRepository creates a new instance of MockScheduleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScheduleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScheduleRepository {
	mock := &MockScheduleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
