// Code generated by mockery v2.50.1. DO NOT EDIT.

package mocks

import (
	context "context"

	ports "github.com/pavozayac/scheduling/src/constraint-service/internal/domain/ports"
	mock "github.com/stretchr/testify/mock"
)

// MockScheduleService is an autogenerated mock type for the ScheduleService type
type MockScheduleService struct {
	mock.Mock
}

type MockScheduleService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScheduleService) EXPECT() *MockScheduleService_Expecter {
	return &MockScheduleService_Expecter{mock: &_m.Mock}
}

// CreateOrModifySchedule provides a mock function with given fields: _a0, _a1
func (_m *MockScheduleService) CreateOrModifySchedule(_a0 context.Context, _a1 ports.ScheduleDTO) (*ports.ScheduleDTO, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrModifySchedule")
	}

	var r0 *ports.ScheduleDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ports.ScheduleDTO) (*ports.ScheduleDTO, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ports.ScheduleDTO) *ports.ScheduleDTO); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.ScheduleDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ports.ScheduleDTO) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockScheduleService_CreateOrModifySchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrModifySchedule'
type MockScheduleService_CreateOrModifySchedule_Call struct {
	*mock.Call
}

// CreateOrModifySchedule is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 ports.ScheduleDTO
func (_e *MockScheduleService_Expecter) CreateOrModifySchedule(_a0 interface{}, _a1 interface{}) *MockScheduleService_CreateOrModifySchedule_Call {
	return &MockScheduleService_CreateOrModifySchedule_Call{Call: _e.mock.On("CreateOrModifySchedule", _a0, _a1)}
}

func (_c *MockScheduleService_CreateOrModifySchedule_Call) Run(run func(_a0 context.Context, _a1 ports.ScheduleDTO)) *MockScheduleService_CreateOrModifySchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ports.ScheduleDTO))
	})
	return _c
}

func (_c *MockScheduleService_CreateOrModifySchedule_Call) Return(_a0 *ports.ScheduleDTO, _a1 error) *MockScheduleService_CreateOrModifySchedule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockScheduleService_CreateOrModifySchedule_Call) RunAndReturn(run func(context.Context, ports.ScheduleDTO) (*ports.ScheduleDTO, error)) *MockScheduleService_CreateOrModifySchedule_Call {
	_c.Call.Return(run)
	return _c
}

// GetSchedule provides a mock function with given fields: _a0, _a1
func (_m *MockScheduleService) GetSchedule(_a0 context.Context, _a1 string) (*ports.ScheduleDTO, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetSchedule")
	}

	var r0 *ports.ScheduleDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ports.ScheduleDTO, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ports.ScheduleDTO); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.ScheduleDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockScheduleService_GetSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSchedule'
type MockScheduleService_GetSchedule_Call struct {
	*mock.Call
}

// GetSchedule is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockScheduleService_Expecter) GetSchedule(_a0 interface{}, _a1 interface{}) *MockScheduleService_GetSchedule_Call {
	return &MockScheduleService_GetSchedule_Call{Call: _e.mock.On("GetSchedule", _a0, _a1)}
}

func (_c *MockScheduleService_GetSchedule_Call) Run(run func(_a0 context.Context, _a1 string)) *MockScheduleService_GetSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockScheduleService_GetSchedule_Call) Return(_a0 *ports.ScheduleDTO, _a1 error) *MockScheduleService_GetSchedule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockScheduleService_GetSchedule_Call) RunAndReturn(run func(context.Context, string) (*ports.ScheduleDTO, error)) *MockScheduleService_GetSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveSchedule provides a mock function with given fields: _a0, _a1
func (_m *MockScheduleService) RemoveSchedule(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for RemoveSchedule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockScheduleService_RemoveSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveSchedule'
type MockScheduleService_RemoveSchedule_Call struct {
	*mock.Call
}

// RemoveSchedule is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockScheduleService_Expecter) RemoveSchedule(_a0 interface{}, _a1 interface{}) *MockScheduleService_RemoveSchedule_Call {
	return &MockScheduleService_RemoveSchedule_Call{Call: _e.mock.On("RemoveSchedule", _a0, _a1)}
}

func (_c *MockScheduleService_RemoveSchedule_Call) Run(run func(_a0 context.Context, _a1 string)) *MockScheduleService_RemoveSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockScheduleService_RemoveSchedule_Call) Return(_a0 error) *MockScheduleService_RemoveSchedule_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockScheduleService_RemoveSchedule_Call) RunAndReturn(run func(context.Context, string) error) *MockScheduleService_RemoveSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockScheduleService creates a new instance of MockScheduleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScheduleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScheduleService {
	mock := &MockScheduleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
