// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForInsertConstraints implements pgx.CopyFromSource.
type iteratorForInsertConstraints struct {
	rows                 []InsertConstraintsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertConstraints) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertConstraints) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ScheduleID,
		r.rows[0].LocationID,
		r.rows[0].TaskID,
		r.rows[0].WorkerID,
		r.rows[0].StartSlot,
		r.rows[0].EndSlot,
		r.rows[0].Kind,
	}, nil
}

func (r iteratorForInsertConstraints) Err() error {
	return nil
}

func (q *Queries) InsertConstraints(ctx context.Context, arg []InsertConstraintsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"constraints"}, []string{"schedule_id", "location_id", "task_id", "worker_id", "start_slot", "end_slot", "kind"}, &iteratorForInsertConstraints{rows: arg})
}
