// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package sqlc

import (
	"context"
)

const getSchedule = `-- name: GetSchedule :one
SELECT id, title from schedules WHERE id = $1
`

func (q *Queries) GetSchedule(ctx context.Context, id int32) (Schedule, error) {
	row := q.db.QueryRow(ctx, getSchedule, id)
	var i Schedule
	err := row.Scan(&i.ID, &i.Title)
	return i, err
}

const getWorker = `-- name: GetWorker :one
SELECT id, title, schedule_id from workers WHERE id = $1
`

func (q *Queries) GetWorker(ctx context.Context, id int32) (Worker, error) {
	row := q.db.QueryRow(ctx, getWorker, id)
	var i Worker
	err := row.Scan(&i.ID, &i.Title, &i.ScheduleID)
	return i, err
}
