// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteLocation = `-- name: DeleteLocation :exec
DELETE FROM locations WHERE id = $1
`

func (q *Queries) DeleteLocation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLocation, id)
	return err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM schedules WHERE id = $1
`

func (q *Queries) DeleteSchedule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSchedule, id)
	return err
}

const deleteScheduleConstraints = `-- name: DeleteScheduleConstraints :exec
DELETE FROM constraints WHERE schedule_id = $1
`

func (q *Queries) DeleteScheduleConstraints(ctx context.Context, scheduleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteScheduleConstraints, scheduleID)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const deleteWorker = `-- name: DeleteWorker :exec
DELETE FROM workers WHERE id = $1
`

func (q *Queries) DeleteWorker(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorker, id)
	return err
}

const getAllConstraintsForLocation = `-- name: GetAllConstraintsForLocation :many
SELECT schedule_id, location_id, task_id, worker_id, start_slot, end_slot, kind from constraints WHERE location_id = $1
`

func (q *Queries) GetAllConstraintsForLocation(ctx context.Context, locationID uuid.UUID) ([]Constraint, error) {
	rows, err := q.db.Query(ctx, getAllConstraintsForLocation, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Constraint
	for rows.Next() {
		var i Constraint
		if err := rows.Scan(
			&i.ScheduleID,
			&i.LocationID,
			&i.TaskID,
			&i.WorkerID,
			&i.StartSlot,
			&i.EndSlot,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllConstraintsForSchedule = `-- name: GetAllConstraintsForSchedule :many
SELECT schedule_id, location_id, task_id, worker_id, start_slot, end_slot, kind from constraints WHERE schedule_id = $1
`

func (q *Queries) GetAllConstraintsForSchedule(ctx context.Context, scheduleID uuid.UUID) ([]Constraint, error) {
	rows, err := q.db.Query(ctx, getAllConstraintsForSchedule, scheduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Constraint
	for rows.Next() {
		var i Constraint
		if err := rows.Scan(
			&i.ScheduleID,
			&i.LocationID,
			&i.TaskID,
			&i.WorkerID,
			&i.StartSlot,
			&i.EndSlot,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllConstraintsForTask = `-- name: GetAllConstraintsForTask :many
SELECT schedule_id, location_id, task_id, worker_id, start_slot, end_slot, kind from constraints WHERE task_id = $1
`

func (q *Queries) GetAllConstraintsForTask(ctx context.Context, taskID uuid.UUID) ([]Constraint, error) {
	rows, err := q.db.Query(ctx, getAllConstraintsForTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Constraint
	for rows.Next() {
		var i Constraint
		if err := rows.Scan(
			&i.ScheduleID,
			&i.LocationID,
			&i.TaskID,
			&i.WorkerID,
			&i.StartSlot,
			&i.EndSlot,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllConstraintsForWorker = `-- name: GetAllConstraintsForWorker :many
SELECT schedule_id, location_id, task_id, worker_id, start_slot, end_slot, kind from constraints WHERE worker_id = $1
`

func (q *Queries) GetAllConstraintsForWorker(ctx context.Context, workerID uuid.UUID) ([]Constraint, error) {
	rows, err := q.db.Query(ctx, getAllConstraintsForWorker, workerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Constraint
	for rows.Next() {
		var i Constraint
		if err := rows.Scan(
			&i.ScheduleID,
			&i.LocationID,
			&i.TaskID,
			&i.WorkerID,
			&i.StartSlot,
			&i.EndSlot,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllLocations = `-- name: GetAllLocations :many
SELECT id, title, story, schedule_id from locations
`

func (q *Queries) GetAllLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.Query(ctx, getAllLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Story,
			&i.ScheduleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSchedules = `-- name: GetAllSchedules :many
SELECT id, title from schedules
`

func (q *Queries) GetAllSchedules(ctx context.Context) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, getAllSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTasks = `-- name: GetAllTasks :many
SELECT id, title, story, schedule_id from tasks
`

func (q *Queries) GetAllTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, getAllTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Story,
			&i.ScheduleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllWorkers = `-- name: GetAllWorkers :many
SELECT id, first_name, last_name, schedule_id from workers
`

func (q *Queries) GetAllWorkers(ctx context.Context) ([]Worker, error) {
	rows, err := q.db.Query(ctx, getAllWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Worker
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.ScheduleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConstraint = `-- name: GetConstraint :one
SELECT schedule_id, location_id, task_id, worker_id, start_slot, end_slot, kind from constraints WHERE location_id = $1 AND task_id = $2 AND worker_id = $3 AND start_slot = $4 AND end_slot = $5 AND kind = $6
`

type GetConstraintParams struct {
	LocationID uuid.UUID
	TaskID     uuid.UUID
	WorkerID   uuid.UUID
	StartSlot  pgtype.Int4
	EndSlot    pgtype.Int4
	Kind       ConstraintType
}

func (q *Queries) GetConstraint(ctx context.Context, arg GetConstraintParams) (Constraint, error) {
	row := q.db.QueryRow(ctx, getConstraint,
		arg.LocationID,
		arg.TaskID,
		arg.WorkerID,
		arg.StartSlot,
		arg.EndSlot,
		arg.Kind,
	)
	var i Constraint
	err := row.Scan(
		&i.ScheduleID,
		&i.LocationID,
		&i.TaskID,
		&i.WorkerID,
		&i.StartSlot,
		&i.EndSlot,
		&i.Kind,
	)
	return i, err
}

const getLocation = `-- name: GetLocation :one
SELECT id, title, story, schedule_id from locations WHERE id = $1
`

func (q *Queries) GetLocation(ctx context.Context, id uuid.UUID) (Location, error) {
	row := q.db.QueryRow(ctx, getLocation, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Story,
		&i.ScheduleID,
	)
	return i, err
}

const getSchedule = `-- name: GetSchedule :one
SELECT id, title from schedules WHERE id = $1
`

func (q *Queries) GetSchedule(ctx context.Context, id uuid.UUID) (Schedule, error) {
	row := q.db.QueryRow(ctx, getSchedule, id)
	var i Schedule
	err := row.Scan(&i.ID, &i.Title)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, title, story, schedule_id from tasks WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Story,
		&i.ScheduleID,
	)
	return i, err
}

const getWorker = `-- name: GetWorker :one
SELECT id, first_name, last_name, schedule_id from workers WHERE id = $1
`

func (q *Queries) GetWorker(ctx context.Context, id uuid.UUID) (Worker, error) {
	row := q.db.QueryRow(ctx, getWorker, id)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.ScheduleID,
	)
	return i, err
}

const insertConstraint = `-- name: InsertConstraint :exec
INSERT INTO constraints (schedule_id, location_id, task_id, worker_id, start_slot, end_slot, kind) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertConstraintParams struct {
	ScheduleID uuid.UUID
	LocationID uuid.UUID
	TaskID     uuid.UUID
	WorkerID   uuid.UUID
	StartSlot  pgtype.Int4
	EndSlot    pgtype.Int4
	Kind       ConstraintType
}

func (q *Queries) InsertConstraint(ctx context.Context, arg InsertConstraintParams) error {
	_, err := q.db.Exec(ctx, insertConstraint,
		arg.ScheduleID,
		arg.LocationID,
		arg.TaskID,
		arg.WorkerID,
		arg.StartSlot,
		arg.EndSlot,
		arg.Kind,
	)
	return err
}

type InsertConstraintsParams struct {
	ScheduleID uuid.UUID
	LocationID uuid.UUID
	TaskID     uuid.UUID
	WorkerID   uuid.UUID
	StartSlot  pgtype.Int4
	EndSlot    pgtype.Int4
	Kind       ConstraintType
}

const insertLocation = `-- name: InsertLocation :exec
INSERT INTO locations (id, title, story, schedule_id) VALUES ($1, $2, $3, $4)
`

type InsertLocationParams struct {
	ID         uuid.UUID
	Title      string
	Story      string
	ScheduleID uuid.UUID
}

func (q *Queries) InsertLocation(ctx context.Context, arg InsertLocationParams) error {
	_, err := q.db.Exec(ctx, insertLocation,
		arg.ID,
		arg.Title,
		arg.Story,
		arg.ScheduleID,
	)
	return err
}

const insertTask = `-- name: InsertTask :exec
INSERT INTO tasks (id, title, story, schedule_id) VALUES ($1, $2, $3, $4)
`

type InsertTaskParams struct {
	ID         uuid.UUID
	Title      string
	Story      string
	ScheduleID uuid.UUID
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) error {
	_, err := q.db.Exec(ctx, insertTask,
		arg.ID,
		arg.Title,
		arg.Story,
		arg.ScheduleID,
	)
	return err
}

const insertWorker = `-- name: InsertWorker :exec
INSERT INTO workers (id, first_name, last_name, schedule_id) VALUES ($1, $2, $3, $4)
`

type InsertWorkerParams struct {
	ID         uuid.UUID
	FirstName  string
	LastName   string
	ScheduleID uuid.UUID
}

func (q *Queries) InsertWorker(ctx context.Context, arg InsertWorkerParams) error {
	_, err := q.db.Exec(ctx, insertWorker,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.ScheduleID,
	)
	return err
}

const upsertLocation = `-- name: UpsertLocation :exec
INSERT INTO locations (id, title, story, schedule_id) VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET title = $2, story = $3, schedule_id = $4
`

type UpsertLocationParams struct {
	ID         uuid.UUID
	Title      string
	Story      string
	ScheduleID uuid.UUID
}

func (q *Queries) UpsertLocation(ctx context.Context, arg UpsertLocationParams) error {
	_, err := q.db.Exec(ctx, upsertLocation,
		arg.ID,
		arg.Title,
		arg.Story,
		arg.ScheduleID,
	)
	return err
}

const upsertSchedule = `-- name: UpsertSchedule :exec
INSERT INTO schedules (id, title) VALUES ($1, $2) 
ON CONFLICT (id) DO UPDATE SET title = $2
`

type UpsertScheduleParams struct {
	ID    uuid.UUID
	Title string
}

func (q *Queries) UpsertSchedule(ctx context.Context, arg UpsertScheduleParams) error {
	_, err := q.db.Exec(ctx, upsertSchedule, arg.ID, arg.Title)
	return err
}

const upsertTask = `-- name: UpsertTask :exec
INSERT INTO tasks (id, title, story, schedule_id) VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET title = $2, story = $3, schedule_id = $4
`

type UpsertTaskParams struct {
	ID         uuid.UUID
	Title      string
	Story      string
	ScheduleID uuid.UUID
}

func (q *Queries) UpsertTask(ctx context.Context, arg UpsertTaskParams) error {
	_, err := q.db.Exec(ctx, upsertTask,
		arg.ID,
		arg.Title,
		arg.Story,
		arg.ScheduleID,
	)
	return err
}

const upsertWorker = `-- name: UpsertWorker :exec
INSERT INTO workers (id, first_name, last_name, schedule_id) VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET first_name = $2, last_name = $3, schedule_id = $4
`

type UpsertWorkerParams struct {
	ID         uuid.UUID
	FirstName  string
	LastName   string
	ScheduleID uuid.UUID
}

func (q *Queries) UpsertWorker(ctx context.Context, arg UpsertWorkerParams) error {
	_, err := q.db.Exec(ctx, upsertWorker,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.ScheduleID,
	)
	return err
}
