name: constraint-service - build and push docker image

on:
  push:
    branches: [develop]
    paths: 
      - src/constraint-service/**
  pull_request: 
    branches: [develop]
    paths: 
      - src/constraint-service/**
  workflow_dispatch: 

env:
  APP_NAME: constraint-service
  REGISTRY: ghcr.io

defaults:
  run:
     working-directory: ./src/constraint-service

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.APP_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=sha,format=short,prefix=,suffix=-${{ github.run_number }},enable=true
      - name: Build and push image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: src/${{ env.APP_NAME }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.APP_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
        
